<?php
/**
 * Created by PhpStorm.
 * User: marcosvinicius
 * Date: 11/06/18
 * Time: 09:14
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{

}