<?php
/**
 * Created by PhpStorm.
 * User: marcosvinicius
 * Date: 18/06/18
 * Time: 14:26
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

}